DEV-2791 Changed current report propagation logic
futurehomeno/edge-easee-adapter pull request #31
Opened 2024-01-08 13:02 UTC by kacperdrobny

2024-01-08 15:21 UTC, rafalmnich requested changes

2024-01-08 15:21 UTC, rafalmnich commented on src/internal/signalr/handler.go
>  	return nil
```suggestion
	return err
```

2024-01-08 15:21 UTC, rafalmnich commented on src/internal/signalr/handler.go
>  	return err
```suggestion
	return err
```

2024-01-09 09:12 UTC, rhstr requested changes
Please apply changes requested by @rafalmnich

2024-01-09 09:14 UTC, rhstr approved these changes

2024-01-09 09:14 UTC, rafalmnich approved these changes

2024-01-09 09:16 UTC, merged